version: "3.7"
services:
  nginx:
    build: ./nginx
    networks: 
      - proxy
    ports:
      - "8080:80"
    links:
      - frontend
      - server

  frontend:
    build: ./frontend
    command: "run start"
    networks: 
      - proxy
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  server:
    build: ./server
    command: "run start"
    networks: 
      - proxy
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - ./data:/data

networks:
  proxy:
